### ISSUE TITLE
Another vfs-ext error on directory listing

### ISSUE THREAD

**Issue by wilsonk** [streaksu/Gloire#8] opened 2024-03-02 03:38 UTC
Similar to issue #7, I logged in and tried to ```mkdir run``` in /var dir, that failed so I 'touch'ed a run file...then I tried to ```mkdir run``` overtop of the 'run' file...this failed, of course. So then I removed the 'run' file and did a ```mkdir run``` and it seemed to work, but then I got this error when I tried to ```ls -al ./run``` in the /var dir:

```
qemu-system-x86_64 -m 5G -hda gloire.img -serial stdio -M q35 -cpu host -enable-kvm    
 WARNING: Image format was not specified for 'gloire.img' and probing guessed raw.    
          Automatically detecting the format is dangerous for raw images, write operations on block 0 will be         restricted.    
          Specify the 'raw' format explicitly to remove the restrictions.    
 (0000000006) x86_64-multiboot2 physical map:                                        
 (0000000006) 00000000000000500000 + 0000000000007FADF000 MEMORY_FREE                
 (0000000006) 0000000000007FFDF000 + 00000000000000021000 MEMORY_RESERVED            
 (0000000006) 000000000000B0000000 + 00000000000010000000 MEMORY_RESERVED            
 (0000000006) 000000000000FED1C000 + 00000000000000004000 MEMORY_RESERVED            
 (0000000006) 000000000000FEFFC000 + 00000000000000004000 MEMORY_RESERVED            
 (0000000006) 000000000000FEFFC000 + 00000000000000004000 MEMORY_RESERVED            
 (0000000006) 00000000000100000000 + 000000000000C0000000 MEMORY_FREE                
 (0000000003) Ironclad 654e6fc                                                       
 (0000000003) Please report bugs at https://ironclad.nongnu.org/usersupport.html     
 (0000000003) Scrollwheel support enabled for mouse                                  
 (0000000003) Searching root 123e4567-e89b-12d3-a456-426614174000                    
 (0000000003) Mounting root sata01p2                                                 
 (0000000003) Booting init /sbin/gcon                                                
 (0000000198)                    --:::-+*.                                  
 (0000000198)   ....             =%%%%%%:++==..:+#:                         
 (0000000198) +*+++++**++=-.      +:%%%%%=+%%%:.-%%.                        
 (0000000198) --=+++=-----=**+.   .+:%%%%*-%%%:.-%%                         
 (0000000198) -=++++++----#@@=#-   -:=%%%%:%%%-.:%%:                        
 (0000000198) ++++++++*@@==%%-+#=   +.%%%#:%%%-.:%%#                        
 (0000000198) +++++++--+==*%%**-#   .+*-   *%%=..#%%+                       
 (0000000198) +++++++=----====-=%    -:            .-                       
 (0000000198) ++++++++=---=+++++%     +                                     
 (0000000198) Panic: Ada exception triggered at vfs-ext.adb:1628            
 Killed    
```

I assume Dir_Name'Length ends up being zero somehow for the Entity.Name_Buffer?

**Comment by streaksu** [comment] 2024-03-02 07:46
Hi! Thanks for reporting.

Right now there are other issues opened tackling issues with `/var/run` and ext2 support within Ironclad. Once those are fixed, I will check to see whether this is reproducible, and possible fixes. Sorry for the inconvenience.

**Comment by streaksu** [comment] 2024-03-08 14:35
I am not able to reproduce after the latest changes, thus, I will close this issue, please reopen it if you are able to reproduce it.

**Closed by streaksu** 2024-03-08 14:35 UTC
