### ISSUE TITLE
`xbstrap install --all` fails (readme instructions)

### ISSUE THREAD

**Issue by ohenley** [streaksu/Gloire#1] opened 2022-05-31 21:18 UTC
When building (xbstrap install --all) I get the following:

```
gcc -DHAVE_CONFIG_H -I. -I/home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas  -I. -I/home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas -I../bfd -I/home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas/config -I/home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas/../include -I/home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas/.. -I/home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas/../bfd -DLOCALEDIR="\"/home/henley/3rd/repos/Gloire/base-files/tools/host-binutils/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -Wwrite-strings -I/home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas/../zlib -O2 -pipe   -MT listing.o -MD -MP -MF $depbase.Tpo -c -o listing.o /home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas/listing.c &&\
mv -f $depbase.Tpo $depbase.Po
/home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas/as.c: In function 'print_version_id':
/home/henley/3rd/repos/Gloire/base-files/../ports/binutils/gas/as.c:237:21: error: 'TARGET_ALIAS' undeclared (first use in this function); did you mean 'TARGET_ARCH'?
  237 |            VERSION, TARGET_ALIAS, BFD_VERSION_STRING);
  ```
Any idea? Thx.

**Comment by streaksu** [comment] 2022-05-31 21:48
I can't reproduce this error message, could you try building again with the [updated instructions](https://github.com/streaksu/Gloire/blob/main/README.md)?
If the issue persists, it would be helpful to know which distribution this is, and whether your toolchain is updated.

**Comment by ohenley** [comment] 2022-05-31 22:14
ubuntu 20.04

see attached file. Thx!
[output.txt](https://github.com/streaksu/Gloire/files/8809710/output.txt)

**Comment by ohenley** [comment] 2022-06-01 15:05
It worked flawlessly! Impressive work. Thank you. 

nb: the doc generation complained the env was missing tex support.

**Comment by streaksu** [comment] 2022-06-01 15:10
The 2 day patch came around quite fast actually, the new utility should make this process much easier as detailed in the new README instructions.
I will close this issue as that new buildsystem should fix this, if any issues arise, please open a new issue, thanks for giving Gloire and Ironclad a try!

**Closed by streaksu** 2022-06-01 15:10 UTC
