### ISSUE TITLE
vfs-ext error when writing file and 'ls'ing dir

### ISSUE THREAD

**Issue by wilsonk** [streaksu/Gloire#7] opened 2024-03-02 03:27 UTC
Due to the X11 version of Gloire not starting (see issue #6), I have logged in to the fallback shell to see how things are working. I thought maybe I would try to add the missing /var/run directory to get past one of the errors in the other issue.

I logged in as root, cd'ed to /var and then tried to ```mkdir run```. This failed with an EINVAL. Then I 'touched' a 'run' file, just to see if I could write to that dir. The 'touch' seemed to work, but when I tried to 'ls' the dir I got this error:
```
qemu-system-x86_64 -m 5G -drive file=gloire.img,format=raw -serial stdio -M q35 -cpu host -enable-kvm
(0000000002) x86_64-multiboot2 physical map:                                    
(0000000002) 00000000000000500000 + 0000000000007FADF000 MEMORY_FREE            
(0000000002) 0000000000007FFDF000 + 00000000000000021000 MEMORY_RESERVED        
(0000000002) 000000000000B0000000 + 00000000000010000000 MEMORY_RESERVED        
(0000000002) 000000000000FED1C000 + 00000000000000004000 MEMORY_RESERVED        
(0000000002) 000000000000FEFFC000 + 00000000000000004000 MEMORY_RESERVED        
(0000000002) 000000000000FEFFC000 + 00000000000000004000 MEMORY_RESERVED        
(0000000002) 00000000000100000000 + 000000000000C0000000 MEMORY_FREE            
(0000000001) Ironclad 654e6fc                                                   
(0000000001) Please report bugs at https://ironclad.nongnu.org/usersupport.html 
(0000000001) Scrollwheel support enabled for mouse                              
(0000000001) Searching root 123e4567-e89b-12d3-a456-426614174000                
(0000000001) Mounting root sata01p2                                             
(0000000001) Booting init /sbin/gcon                                            
(0000000028)                    --:::-+*.                              
(0000000028)   ....             =%%%%%%:++==..:+#:                     
(0000000028) +*+++++**++=-.      +:%%%%%=+%%%:.-%%.                    
(0000000028) --=+++=-----=**+.   .+:%%%%*-%%%:.-%%                     
(0000000028) -=++++++----#@@=#-   -:=%%%%:%%%-.:%%:                    
(0000000028) ++++++++*@@==%%-+#=   +.%%%#:%%%-.:%%#                    
(0000000028) +++++++--+==*%%**-#   .+*-   *%%=..#%%+                   
(0000000028) +++++++=----====-=%    -:            .-                   
(0000000028) ++++++++=---=+++++%     +                                 
(0000000028) Panic: Ada exception triggered at vfs-ext.adb:1019
```

Seems like the Inod.Hard_Link_Count is the failure? Hmmm...anyways, I can see there has been some recent work on vfs-ext, so maybe this hasn't been addressed yet.

**Comment by streaksu** [comment] 2024-03-02 07:45
Hi! Thanks for reporting.

Right now there are other issues opened tackling issues with `/var/run` and ext2 support within Ironclad. Once those are fixed, I will check to see whether this is reproducible, and possible fixes.

**Comment by streaksu** [comment] 2024-03-08 14:36
I am not able to reproduce after the latest changes, thus, I will close this issue, please reopen it if you are able to reproduce it.

**Closed by streaksu** 2024-03-08 14:36 UTC
