### ISSUE TITLE
Failure to start X11 

### ISSUE THREAD

**Issue by wilsonk** [streaksu/Gloire#6] opened 2024-03-02 03:17 UTC
I am getting this set of errors with a newly built system from yesterday (Feb 29, 2024), when attempting to start the graphical Gloire OS (qemu version 8.2.0): 
```
qemu-system-x86_64 -m 5G -drive file=gloire.img,format=raw -serial stdio -M q35 -cpu host -enable-kvm
(0000000002) x86_64-multiboot2 physical map:                                    
(0000000002) 00000000000000500000 + 0000000000007FADF000 MEMORY_FREE            
(0000000002) 0000000000007FFDF000 + 00000000000000021000 MEMORY_RESERVED        
(0000000002) 000000000000B0000000 + 00000000000010000000 MEMORY_RESERVED        
(0000000002) 000000000000FED1C000 + 00000000000000004000 MEMORY_RESERVED        
(0000000002) 000000000000FEFFC000 + 00000000000000004000 MEMORY_RESERVED        
(0000000002) 000000000000FEFFC000 + 00000000000000004000 MEMORY_RESERVED        
(0000000002) 00000000000100000000 + 000000000000C0000000 MEMORY_FREE            
(0000000001) Ironclad 654e6fc                                                   
(0000000001) Please report bugs at https://ironclad.nongnu.org/usersupport.html 
(0000000001) Scrollwheel support enabled for mouse                              
(0000000001) Searching root 123e4567-e89b-12d3-a456-426614174000                
(0000000001) Mounting root sata01p2                                             
(0000000001) Booting init /sbin/init                                            
Epoch Init System 1.3.0 "Fluoxetine"
Mounting /etc/fstab partitions ... Done
Starting metalog ... Done
Starting crond ... crond: can't open or create /var/run/crond.pid: I/O error (EIO)
mlibc: syslog: connect returned an error, falling back to infoLogger
mlibc: syslog: (CRON) DEATH (can't open or create /var/run/crond.pid): I/O error (EIO)
FAIL
Starting Xorg ... Done
Starting SLiM ... Done
(EE) 
Fatal server error:
(EE) Linking lock file (/tmp/.X0-lock) in place failed: Invalid argument (EINVAL)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) 
rtdl: DT_SYMBOLIC is not implemented correctly!
rtdl: DT_SYMBOLIC is not implemented correctly!
rtdl: DT_SYMBOLIC is not implemented correctly!
slim: Stale lockfile found, removing it
mlibc: uselocale() is a no-op
sh: line 1: /usr/bin/xauth: No such file or directory (ENOENT)
Unrecognized option: vt07
```

Seems like the lock file can't be written/linked and the cron file can't be created (/var/run dir is missing on first run of vm, btw). Then at the end the 'vt07' option is not recognized?? Not sure what that should be instead.

**Comment by streaksu** [comment] 2024-03-02 07:24
Hello! Thanks for reporting the issue. I will try to address the problems 1 by 1:

- `xauth`: Your install seems to not have `xorg-xauth`, or the system is otherwise unable to find it. `xauth` is not a dependency of `slim`, but it should otherwise be installed by using `./jinx build-all`, so I didn't notice. I will fix the slim recipe to hard-depend on xauth. Could you try running it with said package installed and see whether that fixes that error?

- `vt07`: As to the `vt07` and others, those errors are to be expected, and should not lead to failed execution.

- Fatal server error: The way Xorg is started in Gloire requires for the Xorg server to have its lock files deleted at the end of execution, due to bad support of termination signals (Xorg cannot clean after itself if we dont tell it to clean properly). This cleanup is done by the init system when shutting down or rebooting. If the machine is turned off without notifying the init system, say, closing the window of an emulator, this cleanup will never happen, and Xorg will fail to start. If this is the issue, rebuilding the image, or otherwise entering on the system and deleting the lock file, will make it work.

**Comment by wilsonk** [comment] 2024-03-02 13:19
1.  Ok thanks for the explanation. I will await a fix for this one.
2. Hmm, not sure how to add the xauth package and retry explicitly. The makeiso.sh step seems to install libxauth wihtou error, though?
3. Ok on this one.
4. Thanks for the info...I had done a hard shutdown and that would be the reason for that. I rebuilt and things seems to work fine, even without the xauth package.

**Comment by streaksu** [comment] 2024-03-04 08:23
Here is the progress and fixes done:

- `/var/run` woes: Fixed with 20f26d10b8c67d91cb068204f713f264d79b5fe7.
- `xauth`: I imagine this had to do with some filesystem corruption related to turning off the system not cleanly, its ext2 after all, and I am not able to reproduce. `xauth` was added as a dependency with b1c84557f0eb90b0ce2944d324e7473ba3f4a267.
- `vt07`: Fixed with d9c787fec0425c63ff1d43ba65e72dc2bef5fc29, 5ce6ea5ef26972703c102e9b6d49cb66b3b02a42, and b1c84557f0eb90b0ce2944d324e7473ba3f4a267.
- Fatal server error: Immediate cause was the non clean turning off, I will work on proper termination support at some point.

Given the only remaining issue to fix is the termination issue, and that is a more long term endeavor that is tangentially related to the issue at hand, I will take this issue as a whole as fixed.

In case this commits don't fix the issue at hand for you, please reopen the issue. Thank you for the report, I truly appreciate it.

![20141106185423-5-powerful-ways-give-thanks-your-people(1)](https://github.com/streaksu/Gloire/assets/30004048/7ef6de50-9187-4bcc-82c7-3608113dbe11)

**Closed by streaksu** 2024-03-04 08:23 UTC

**Comment by krionical** [comment] 2024-06-14 23:03
Possibly similar problem:

> emu-system-x86_64 -m 5G -drive file=gloire.img,format=raw -serial stdio -M q35 -cpu host -enable-kvm
> (0000000003) x86_64-multiboot2 physical map:                                    
> (0000000003) 00000000000000500000 + 0000000000007FADF000 MEMORY_FREE            
> (0000000003) 0000000000007FFDF000 + 00000000000000021000 MEMORY_RESERVED        
> (0000000003) 000000000000B0000000 + 00000000000010000000 MEMORY_RESERVED        
> (0000000003) 000000000000FED1C000 + 00000000000000004000 MEMORY_RESERVED        
> (0000000003) 000000000000FEFFC000 + 00000000000000004000 MEMORY_RESERVED        
> (0000000003) 000000000000FEFFC000 + 00000000000000004000 MEMORY_RESERVED        
> (0000000003) 00000000000100000000 + 000000000000C0000000 MEMORY_FREE            
> (0000000002) Ironclad 8649cd9                                                   
> (0000000002) Please report bugs at https://ironclad.nongnu.org/usersupport.html 
> (0000000003) Searching root 123e4567-e89b-12d3-a456-426614174000                
> (0000000003) Mounting root sata01p2                                             
> (0000000003) Booting init /sbin/init                                            
> Epoch Init System 1.3.0 "Fluoxetine"
> Mounting /etc/fstab partitions ... Done
> Starting metalog ... Done
> Starting crond ... Done
> Starting Xorg ... Done
> Starting JWM ... Done
> mlibc: getsockopt() call with SOL_SOCKET and SO_SNDBUF is unimplemented
> mlibc: setsockopt() call with SOL_SOCKET and SO_SNDBUF is unimplemented
> 
> X.Org X Server 1.21.1.11
> X Protocol Version 11, Revision 0
> Current Operating System: Ironclad thehomeoftheseal 8649cd9 8649cd9 x86_64-multiboot2
>  
> Current version of pixman: 0.42.2
> 	Before reporting problems, check http://wiki.x.org
> 	to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
> 	(++) from command line, (!!) notice, (II) informational,
> 	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (==) Log file: "/var/log/Xorg.0.log", Time: Fri Jun 14 22:5738 2024
> (==) Using config file: "/etc/X11/xorg.conf"
> rtdl: DT_SYMBOLIC is not implemented correctly!
> rtdl: DT_SYMBOLIC is not implemented correctly!
> rtdl: DT_SYMBOLIC is not implemented correctly!
> mlibc: getsockopt() call with SOL_SOCKET and SO_SNDBUF is unimplemented
> mlibc: setsockopt() call with SOL_SOCKET and SO_SNDBUF is unimplemented
> In function pthread_setname_np, file ../../../base_dir/sources/mlibc/options/posix/generic/pthread-stubs.cpp:453
> __ensure(Library function fails due to missing sysdep) failed
> In function tcflush, file ../../../base_dir/sources/mlibc/options/posix/generic/termios-stubs.cpp:65
> __ensure(Library function fails due to missing sysdep) failed
> In function tcflush, file ../../../base_dir/sources/mlibc/options/posix/generic/termios-stubs.cpp:65
> __ensure(Library function fails due to missing sysdep) failed
> mlibc: sys_prepare_stack() does not setup a guard!
> In function pthread_setname_np, file ../../../base_dir/sources/mlibc/options/posix/generic/pthread-stubs.cpp:453
> __ensure(Library function fails due to missing sysdep) failed
> mlibc: uselocale() is a no-op
> JWM: warning: could not load font: Sans-12:bold
> JWM: warning: could not load font: Sans-12
> JWM: warning: could not load font: Sans-12
> JWM: warning: could not load font: Sans-12
> JWM: warning: could not load font: Sans-12
> JWM: warning: could not load font: Sans-12
> JWM: warning: could not load font: Sans-12
> JWM: warning: could not load font: Sans-12

Eventually comes up, but she's slow.

**Comment by streaksu** [comment] 2024-06-15 11:30
Seems like the release you are testing this with is pretty old. I have released [a new one](https://github.com/streaksu/Gloire/releases/tag/2024-06-15) that should have different behavior, sorry for the inconvenience.

**Comment by krionical** [comment] 2024-06-15 17:20
Asks for a user and a pass, which I assume is blank. Hit enter, eventually boots, but slowly. No output in console. Opening a game results in a freezing behavior where the window won't close and I have to shut the machine off with force.
